### ISSUE TITLE
Tensorflow issue prohibiting server.py to run

### ISSUE THREAD

**Issue by ZenaMel** [joel-simon/ganbreeder#21]
Traceback:

```
Traceback (most recent call last):
  File "d:\Open-Source\AI\ganbreeder\gan_server\server.py", line 6, in <module>
    import tensorflow as tf
  File "C:\Python38\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Python38\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 114
    def TFE_ContextOptionsSetAsync(arg1, async):
                                         ^
SyntaxError: invalid syntax
```

OS: Windows 10

pip freeze:

```

Flask                            1.0.2
Flask-Cors                       3.0.7
Pillow                           7.0.0
scipy                            1.5.2
tensorflow                       1.8.0
tensorflow-hub                   0.9.0
```

**Comment by ZenaMel** [comment]
This happened because I am running Python 3.7 and not 3.6

For anyone experiencing this issue: https://github.com/tensorflow/tensorflow/issues/20690
