### ISSUE TITLE
setuptools requirement is missing and in tensorflow might be old in requirements.txt

### ISSUE THREAD

**Issue by owlen** [joel-simon/ganbreeder#23]
`setuptools` isn't mentioned and I believe it's a requirement.

In addition, the requirement
`tensorflow==1.12.0`
might be too strict. At the time of writing, my pip couldn't find this version, so I changed it to
`tensorflow>=1.12.0`
and the requirement phase passed.

**Comment by owlen** [comment]
Just realized that dependabot added PRs for bumping the tensorflow version.

**Comment by regtable** [comment]
saved me a long time here cheers!
spoke too soon. many errors. wheels pillows and god knows what

**Comment by Zeesy** [comment]
Any updates on this? Just installing today, getting this error when requirements.txt has `tensorflow==1.12.0`:
```
ERROR: Could not find a version that satisfies the requirement tensorflow==1.12.0 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0)
ERROR: No matching distribution found for tensorflow==1.12.0
```
I have also tried running `python server.py` with tensorflow-gpu>==2.5.0 and updating the other requirements. This results in this error:
```
AttributeError: module 'tensorflow' has no attribute 'GraphKeys'
bash: AttributeError:: command not found
```


This error pops up after changing it to `tensorflow>==1.12.0`:
```
Collecting Flask==1.0.2
  Using cached Flask-1.0.2-py2.py3-none-any.whl (91 kB)
Collecting Flask-Cors==3.0.7
  Using cached Flask_Cors-3.0.7-py2.py3-none-any.whl (13 kB)
Collecting tensorflow>==1.12.0
  Downloading tensorflow-2.5.0-cp39-cp39-win_amd64.whl (422.6 MB)
Collecting tensorflow_hub==0.2.0
  Downloading tensorflow_hub-0.2.0-py2.py3-none-any.whl (66 kB)
Collecting scipy==1.1.0
  Downloading scipy-1.1.0.tar.gz (15.6 MB)
Collecting Pillow==5.3.0
  Downloading Pillow-5.3.0.tar.gz (15.6 MB)
Collecting Jinja2>=2.10
  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting itsdangerous>=0.24
  Downloading itsdangerous-2.0.1-py3-none-any.whl (18 kB)
Collecting Werkzeug>=0.14
  Downloading Werkzeug-2.0.1-py3-none-any.whl (288 kB)
Requirement already satisfied: click>=5.1 in c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages (from Flask==1.0.2->-r requirements.txt (line 1)) (7.1.2)
Requirement already satisfied: Six in c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages (from Flask-Cors==3.0.7->-r requirements.txt (line 2)) (1.16.0)
Collecting protobuf>=3.4.0
  Downloading protobuf-3.17.3-py2.py3-none-any.whl (173 kB)
Collecting numpy>=1.12.0
  Using cached numpy-1.20.3-cp39-cp39-win_amd64.whl (13.7 MB)
Collecting gast==0.4.0
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting grpcio~=1.34.0
  Downloading grpcio-1.34.1-cp39-cp39-win_amd64.whl (2.9 MB)
Collecting wheel~=0.35
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting keras-preprocessing~=1.1.2
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting Six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting tensorboard~=2.5
  Downloading tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
Collecting wrapt~=1.12.1
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Collecting flatbuffers~=1.12.0
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting absl-py~=0.10
  Downloading absl_py-0.13.0-py3-none-any.whl (132 kB)
Collecting astunparse~=1.6.3
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting numpy>=1.12.0
  Downloading numpy-1.19.5-cp39-cp39-win_amd64.whl (13.3 MB)
Collecting opt-einsum~=3.3.0
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting google-pasta~=0.2
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting tensorflow-estimator<2.6.0,>=2.5.0rc0
  Downloading tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)
Collecting h5py~=3.1.0
  Downloading h5py-3.1.0-cp39-cp39-win_amd64.whl (2.7 MB)
Collecting typing-extensions~=3.7.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting keras-nightly~=2.5.0.dev
  Downloading keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)
Collecting termcolor~=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1-cp39-cp39-win_amd64.whl (14 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.4-py3-none-any.whl (97 kB)
Collecting google-auth<2,>=1.6.3
  Downloading google_auth-1.31.0-py2.py3-none-any.whl (147 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.4-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages (from tensorboard~=2.5->tensorflow>==1.12.0->-r requirements.txt (line 3)) (56.0.0)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting requests<3,>=2.21.0
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow>==1.12.0->-r requirements.txt (line 3)) (3.0.4)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)
Using legacy 'setup.py install' for scipy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for Pillow, since package 'wheel' is not installed.
Using legacy 'setup.py install' for termcolor, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
Installing collected packages: urllib3, pyasn1, idna, certifi, Six, rsa, requests, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, MarkupSafe, google-auth, wheel, Werkzeug, tensorboard-plugin-wit, tensorboard-data-server, protobuf, numpy, markdown, Jinja2, itsdangerous, grpcio, google-auth-oauthlib, absl-py, wrapt, typing-extensions, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, keras-nightly, h5py, google-pasta, gast, flatbuffers, Flask, astunparse, tensorflow-hub, tensorflow, scipy, Pillow, Flask-Cors
  Attempting uninstall: idna
    Found existing installation: idna 3.1
    Uninstalling idna-3.1:
      Successfully uninstalled idna-3.1
  Attempting uninstall: Six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
    Running setup.py install for wrapt: started
    Running setup.py install for wrapt: finished with status 'done'
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.0
    Uninstalling typing-extensions-3.10.0.0:
      Successfully uninstalled typing-extensions-3.10.0.0
    Running setup.py install for termcolor: started
    Running setup.py install for termcolor: finished with status 'done'
    Running setup.py install for scipy: started
    Running setup.py install for scipy: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\zeesy\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zeesy\\AppData\\Local\\Temp\\pip-install-evkwymhh\\scipy_1d9a447ea4e4496caf95b22b4f5102a7\\setup.py'"'"'; __file__='"'"'C:\\Users\\zeesy\\AppData\\Local\\Temp\\pip-install-evkwymhh\\scipy_1d9a447ea4e4496caf95b22b4f5102a7\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zeesy\AppData\Local\Temp\pip-record-vk1uz1c_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\zeesy\appdata\local\programs\python\python39\Include\scipy'
         cwd: C:\Users\zeesy\AppData\Local\Temp\pip-install-evkwymhh\scipy_1d9a447ea4e4496caf95b22b4f5102a7\
    Complete output (150 lines):
    C:\Users\zeesy\AppData\Local\Temp\pip-install-evkwymhh\scipy_1d9a447ea4e4496caf95b22b4f5102a7\setup.py:114: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    lapack_opt_info:
    lapack_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['c:\\users\\zeesy\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\zeesy\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['c:\\users\\zeesy\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\zeesy\\appdata\\local\\programs\\python\\python39\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Found executable C:\Program Files\Git\usr\bin\DF.exe
    Could not locate executable C:\Program
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['c:\\users\\zeesy\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\zeesy\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['c:\\users\\zeesy\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\zeesy\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\lib
      libraries tatlas,tatlas not found in c:\users\zeesy\appdata\local\programs\python\python39\lib
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\libs
      libraries tatlas,tatlas not found in c:\users\zeesy\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\lib
      libraries satlas,satlas not found in c:\users\zeesy\appdata\local\programs\python\python39\lib
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\libs
      libraries satlas,satlas not found in c:\users\zeesy\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\lib
      libraries ptf77blas,ptcblas,atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\lib
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\libs
      libraries ptf77blas,ptcblas,atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\lib
      libraries f77blas,cblas,atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\lib
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\libs
      libraries f77blas,cblas,atlas not found in c:\users\zeesy\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['c:\\users\\zeesy\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\zeesy\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE

    c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\zeesy\AppData\Local\Temp\pip-install-evkwymhh\scipy_1d9a447ea4e4496caf95b22b4f5102a7\setup.py", line 474, in <module>
        setup_package()
      File "C:\Users\zeesy\AppData\Local\Temp\pip-install-evkwymhh\scipy_1d9a447ea4e4496caf95b22b4f5102a7\setup.py", line 470, in setup_package
        setup(**metadata)
      File "c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\zeesy\AppData\Local\Temp\pip-install-evkwymhh\scipy_1d9a447ea4e4496caf95b22b4f5102a7\setup.py", line 388, in configuration
        config.add_subpackage('scipy')
      File "c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 1018, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 984, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 1018, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 984, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "c:\users\zeesy\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 19, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\zeesy\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zeesy\\AppData\\Local\\Temp\\pip-install-evkwymhh\\scipy_1d9a447ea4e4496caf95b22b4f5102a7\\setup.py'"'"'; __file__='"'"'C:\\Users\\zeesy\\AppData\\Local\\Temp\\pip-install-evkwymhh\\scipy_1d9a447ea4e4496caf95b22b4f5102a7\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zeesy\AppData\Local\Temp\pip-record-vk1uz1c_\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\zeesy\appdata\local\programs\python\python39\Include\scipy' Check the logs for full command output.
```

**Comment by gustvdsanden** [comment]
This works with python version 3.6.x (i have 3.6.2) the from 3.7 on python only supports tensorflow 2.x
