### ISSUE TITLE
Tensorflow and javascript errors, configuration issue ?

### ISSUE THREAD

**Issue by lweingart** [joel-simon/ganbreeder#39]
Hello guys,

I'm trying to make this thing working by following the readme but I get stuck at some point.
I'm using 
Ubuntu 18.04
Python 3.6.9
Tensorflow 1.12

It seems to fail when I run 
```
node make_randoms.js
```
and I'm having difficulties pin pointing the reason.
Maybe it comes from my server/secrets.js file? I have to admit that I'm not sure what value I should put for
```
connection: {
            host: "",
```
and I left it empty.

Anyway, here is the log from the server.py:
```
 * Debugger is active!
 * Debugger PIN: 558-604-792
127.0.0.1 - - [12/Feb/2022 21:31:54] "GET / HTTP/1.1" 200 -
Random 24
2022-02-12 21:49:37.006871: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2022-02-12 21:49:37.015832: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2022-02-12 21:49:37.122234: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2022-02-12 21:49:37.130529: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2022-02-12 21:49:41.363498: W tensorflow/core/framework/allocator.cc:122] Allocation of 2684354560 exceeds 10% of system memory.
2022-02-12 21:49:49.669616: W tensorflow/core/framework/allocator.cc:122] Allocation of 2684354560 exceeds 10% of system memory.
Finished in 20.853251218795776
127.0.0.1 - - [12/Feb/2022 21:49:57] "POST /random HTTP/1.1" 200 -

```

and here is the log from `node make_randoms.js`:
```
$ node make_randoms.js
{ Error: ENOENT: no such file or directory, open 'public/img/3ae730976a4f4ed36d399830.jpeg'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at module.exports (/home/argos/git/ganbreeder/server/save_results.js:26:16)
    at <anonymous>
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'public/img/3ae730976a4f4ed36d399830.jpeg' }
```

Could you please help me get back on track? Any help would be greatly appreciated.
Thank you

Cheers

**Comment by lweingart** [comment]
Hi again,

Actually when looking at the previous log:
```
$ node make_randoms.js
{ Error: ENOENT: no such file or directory, open 'public/img/3ae730976a4f4ed36d399830.jpeg'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at module.exports (/home/argos/git/ganbreeder/server/save_results.js:26:16)
    at <anonymous>
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'public/img/3ae730976a4f4ed36d399830.jpeg' }
```

we can see that it attempts to open a public/img/xxx path.
However, there is no public/img directory, but a public/image one.

In the end I was able to make everything to work by fixing this...
I will therefore close this issue.

Thank you

Cheers
